export const CHANGE_USERINFO = "CHANGE_USERINFO";
export const USERINFO_LOADING = "USERINFO_LOADING";
export const USERINFO_LOADED = "USERINFO_LOADED";
export const USERINFO_ERROR = "USERINFO_ERROR";

